### PR TITLE
feat!: rm arrow-line rule, embed peer deps, add node.js support

### PR DESCRIPTION
**Pull request by krampstudio**
- Remove the rule [implicit-arrow-linebreak](https://eslint.org/docs/rules/implicit-arrow-linebreak#enforce-the-location-of-arrow-function-bodies-with-implicit-returns-implicit-arrow-linebreak) because Prettier is not able to support it 
 - Embed peerDependencies of all plugins to prevent all consumers to keep them updated and in sync with the rules
 - Add a simple node.js config (to be improved) 

How to test: 
 - try the branch on one of your project and check the eslint report

### CODE REVIEW

**Review by andrey-ponamarev — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] The feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request's target is not `master`

**Comment by adriloma** [comment]
I get this error when trying to run in, should I use a different eslint version?

image

**Comment by krampstudio** [comment]
> I get this error when trying to run in, should I use a different eslint version?
> 
> image

@adriloma thanks for having a look. 
Do you have `eslint-plugin-jsdoc` in your project ? this is due to a previous version of that plugin. 
The goal of this PR is to prevent you maintain those versions in your projects, so can you please try to remove all eslint plugins from your project and retest ?

**Review by btamas — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] The feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request's target is not `master`

**Review by adriloma — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] bumping versions are applied (if applicable)

**Pull request merged**
